package com.toolproject.runtop.tool_logstatistics.statistics;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATISTICS".
 */
public class Statistics {

	private Long id;
	private String logInfoCommand;

	public Statistics() {
	}

	public Statistics(Long id) {
		this.id = id;
	}

	public Statistics(Long id, String logInfoCommand) {
		this.id = id;
		this.logInfoCommand = logInfoCommand;
	}

	public Statistics(String logInfoCommand) {
		this.logInfoCommand = logInfoCommand;
	}

	@Override
	public String toString() {
		return logInfoCommand;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLogInfoCommand() {
		return logInfoCommand;
	}

	public void setLogInfoCommand(String logInfoCommand) {
		this.logInfoCommand = logInfoCommand;
	}

}
